repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: block-ds-store
        name: Block .DS_Store commits
        language: fail
        entry: ".DS_Store files should not be committed"
        files: \.DS_Store$

      - id: block-pycache
        name: Block __pycache__ commits
        language: fail
        entry: "__pycache__ files should not be committed"
        files: __pycache__/
